import re

file_path = r"D:\AntiGravity\Latest_Active_Apps\InventorySuit_V2_Development\frontend\src\pages\AdminPanel.tsx"

with open(file_path, 'r', encoding='utf-8') as f:
    content = f.read()

# 1. Update the sidebar Settings button
sidebar_pattern = r"""<button className="w-full flex items-center gap-3 px-2 py-2 rounded-lg transition-colors 
hover:bg-slate-800 hover:text-white">
                <Settings className="w-5 h-5" /> Settings
              </button>"""
# Remove the newlines for a robust regex, or use string replace
sidebar_target = """<button className="w-full flex items-center gap-3 px-2 py-2 rounded-lg transition-colors hover:bg-slate-800 hover:text-white">
                <Settings className="w-5 h-5" /> Settings
              </button>"""
sidebar_replacement = """<button 
                onClick={() => setActiveView('settings')}
                className={`w-full flex items-center gap-3 px-2 py-2 rounded-lg transition-colors ${activeView === 'settings' ? 'bg-indigo-600/10 text-indigo-400' : 'hover:bg-slate-800 hover:text-white'}`}
              >
                <Settings className="w-5 h-5" /> Settings
              </button>"""

# Normalize spaces for replacement
import textwrap
content = content.replace(
    '<button className="w-full flex items-center gap-3 px-2 py-2 rounded-lg transition-colors \nhover:bg-slate-800 hover:text-white">\n                <Settings className="w-5 h-5" /> Settings\n              </button>',
    sidebar_replacement
)

# Alternative just in case it didn't match
content = re.sub(
    r'<button className="w-full flex items-center gap-3 px-2 py-2 rounded-lg transition-colors\s*hover:bg-slate-800 hover:text-white">\s*<Settings className="w-5 h-5" /> Settings\s*</button>',
    sidebar_replacement,
    content
)

# 2. Add 'settings' to AdminView type if not already
if "'settings'" not in content:
    content = re.sub(
        r"type AdminView = 'dashboard' \| 'users' \| 'roles' \| 'permissions' \| 'pending' \| 'apps' \| 'extensions' \| 'logs';",
        r"type AdminView = 'dashboard' | 'users' | 'roles' | 'permissions' | 'pending' | 'apps' | 'extensions' | 'logs' | 'settings';",
        content
    )

# 3. Add the settings view at the end of the views
view_block = """            {activeView === 'settings' && (
              <div className="max-w-7xl mx-auto flex flex-col h-full pb-8">
                <div className="flex items-center justify-between mb-6">
                  <h2 className="text-lg font-bold text-slate-800">System Settings</h2>
                </div>
                <div className="bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden">
                  <div className="p-6 border-b border-slate-100">
                    <h3 className="text-md font-bold text-slate-800 mb-1">Data Management</h3>
                    <p className="text-sm text-slate-500">Clear generated data from applications to free up database storage space. Warning: This cannot be undone.</p>
                  </div>
                  <div className="p-6 space-y-6">
                    <div className="flex items-center justify-between p-4 border border-red-200 bg-red-50 rounded-xl">
                      <div>
                        <h4 className="font-bold text-red-800">Clear Salesman App Data</h4>
                        <p className="text-sm text-red-600 mt-1">Permanently deletes all Sales Orders and Payments generated by the Salesman Mobile App.</p>
                      </div>
                      <button 
                        onClick={async () => {
                          if (window.confirm("Are you sure? Type 'CLEAR' to confirm deletion of all Salesman data.")) {
                            const input = window.prompt("Type CLEAR to confirm:");
                            if (input === 'CLEAR') {
                              try {
                                const { remove, ref } = await import('firebase/database');
                                await remove(ref(database, 'sales_orders'));
                                await remove(ref(database, 'sales_payments'));
                                alert("Salesman data cleared successfully.");
                              } catch(e: any) { alert("Error: " + e.message); }
                            } else { alert("Cancelled."); }
                          }
                        }}
                        className="px-4 py-2 bg-red-600 text-white rounded-lg font-bold hover:bg-red-700 transition-colors shadow-sm shadow-red-200"
                      >
                        Clear Data
                      </button>
                    </div>

                    <div className="flex items-center justify-between p-4 border border-red-200 bg-red-50 rounded-xl">
                      <div>
                        <h4 className="font-bold text-red-800">Clear Scanner App Data</h4>
                        <p className="text-sm text-red-600 mt-1">Permanently deletes all scanned trips and scanning history generated by the Scanner Mobile App.</p>
                      </div>
                      <button 
                        onClick={async () => {
                          if (window.confirm("Are you sure? Type 'CLEAR' to confirm deletion of all Scanner data.")) {
                            const input = window.prompt("Type CLEAR to confirm:");
                            if (input === 'CLEAR') {
                              try {
                                const { remove, ref } = await import('firebase/database');
                                await remove(ref(database, 'scanner_trips'));
                                await remove(ref(database, 'mobile_scans'));
                                await remove(ref(database, 'scanner_tracking'));
                                await remove(ref(database, 'scanner_tracking_v2'));
                                alert("Scanner data cleared successfully.");
                              } catch(e: any) { alert("Error: " + e.message); }
                            } else { alert("Cancelled."); }
                          }
                        }}
                        className="px-4 py-2 bg-red-600 text-white rounded-lg font-bold hover:bg-red-700 transition-colors shadow-sm shadow-red-200"
                      >
                        Clear Data
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            )}
          </div>
          
          {/* Slideover panel */}"""

content = content.replace('          </div>\n          \n          {/* Slideover panel */}', view_block)

# Fix title for activeView settings
header_title_pattern = r"\{activeView === 'users' && 'Users'\}"
header_title_replacement = r"{activeView === 'users' && 'Users'}\n                {activeView === 'settings' && 'Settings'}"
if "activeView === 'settings' && 'Settings'" not in content:
    content = re.sub(header_title_pattern, header_title_replacement, content)

with open(file_path, 'w', encoding='utf-8') as f:
    f.write(content)

print("Updated AdminPanel.tsx successfully.")
