export enum BusinessEventType {
  // Inventory Events
  SHIPMENT_RECEIVED = 'SHIPMENT_RECEIVED',
  STOCK_TRANSFERRED = 'STOCK_TRANSFERRED',
  INVENTORY_ADJUSTED = 'INVENTORY_ADJUSTED',
  DAILY_COUNT_COMPLETED = 'DAILY_COUNT_COMPLETED',
  
  // Sales Events
  ORDER_CREATED = 'ORDER_CREATED',
  ORDER_APPROVED = 'ORDER_APPROVED',
  ORDER_DISPATCHED = 'ORDER_DISPATCHED',
  ORDER_CANCELLED = 'ORDER_CANCELLED',

  // Workflow Engine Events
  PURCHASE_CREATED = 'PURCHASE_CREATED',
  PURCHASE_APPROVED = 'PURCHASE_APPROVED',
  ORDER_DELIVERED = 'ORDER_DELIVERED',
  STOCK_RESERVED = 'STOCK_RESERVED',
  STOCK_DEDUCTED = 'STOCK_DEDUCTED',

  ORDER_REJECTED = 'ORDER_REJECTED',

  // Ledger Events
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  PAYMENT_VERIFIED = 'PAYMENT_VERIFIED',
  PAYMENT_REJECTED = 'PAYMENT_REJECTED',
  PAYMENT_APPROVED = 'PAYMENT_APPROVED',

  // Admin Events
  USER_UPDATED = 'USER_UPDATED',
  FAILED_SYNC = 'FAILED_SYNC',
  SECURITY_WARNING = 'SECURITY_WARNING',
  USER_LOGIN = 'USER_LOGIN',

  // Catalog / Pricing
  PRICE_UPDATED = 'PRICE_UPDATED',
  
  // Notifications / Inventory (Specific)
  ROOM_ASSIGNED = 'ROOM_ASSIGNED',
  SHIPMENT_ASSIGNED = 'SHIPMENT_ASSIGNED',
  COUNT_SUBMITTED = 'COUNT_SUBMITTED',
  COUNT_APPROVED = 'COUNT_APPROVED',
  COUNT_REJECTED = 'COUNT_REJECTED',
  LOW_STOCK = 'LOW_STOCK',
}

export interface BusinessEvent<T = any> {
  type: BusinessEventType;
  payload: T;
  userId: string;
  timestamp: number;
}
